[book]
authors = ["windmissing"]
language = "en"
description = "The note of GAMES103"
multilingual = false
src = "src"
title = "GAMES103"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/CaterpillarStudyGroup/GAMES103_mdbook"
git-repository-icon = "fa-github"
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js", "theme/mermaid.min.js", "theme/mermaid-init.js"]

[output.html.fold]

[output.html.print]
enable = true

[output.html.search]
enable = true

# [output.pdf]




